apiVersion: v1
kind: ReplicationController
metadata:
  name: keycloak-proxy
  labels:
    name: keycloak-proxy
spec:
  replicas: 1
  selector:
    name: keycloak-proxy
  template:
    metadata:
      labels:
        name: keycloak-proxy
    spec:
      containers:
      - name: keycloak-proxy
        image: quay.io/gambol99/keycloak-proxy:latest
        imagePullPolicy: Always
        args:
          - --config /etc/secrets/forwarding.yml
          #- --discovery-url https://sso.example.com/auth/realms/hod-test
          - --client-id broker
          #- --client-secret
          - --listen 127.0.0.1:3000
          - --enable-forwarding true
          #- --forwarding-username username
          #- --forwarding-password password
          - --log-requests true
          - --log-json-format true
          - --verbose true
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
      volumes:
      - name: secrets
        secret:
          secretName: config
